-- ----------------------------
-- Table structure for persons
-- ----------------------------
CREATE TABLE IF NOT EXISTS persons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_of_birth DATE,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    national_id VARCHAR(255) NOT NULL,
    CONSTRAINT UK_persons_national_id UNIQUE (national_id)
);

-- ----------------------------
-- Table structure for drivers_licenses
-- ----------------------------
CREATE TABLE IF NOT EXISTS drivers_licenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expiry_date DATE,
    issue_date DATE,
    license_number VARCHAR(255) NOT NULL,
    person_id BIGINT,
    CONSTRAINT UK_drivers_licenses_license_number UNIQUE (license_number),
    CONSTRAINT UK_drivers_licenses_person_id UNIQUE (person_id),
    CONSTRAINT FK_drivers_licenses_person FOREIGN KEY (person_id) REFERENCES persons(id)
);

-- ----------------------------
-- Table structure for license_categories
-- ----------------------------
CREATE TABLE IF NOT EXISTS license_categories (
    license_id BIGINT NOT NULL,
    category VARCHAR(255),
    CONSTRAINT FK_license_categories_license FOREIGN KEY (license_id) REFERENCES drivers_licenses(id)
);

-- ----------------------------
-- Table structure for vehicle_type
-- ----------------------------
CREATE TABLE IF NOT EXISTS vehicle_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_type VARCHAR(255) NOT NULL,
    CONSTRAINT UK_vehicle_type UNIQUE (vehicle_type)
);

-- ----------------------------
-- Table structure for vehicles
-- ----------------------------
CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color VARCHAR(255),
    company VARCHAR(255),
    engine_number VARCHAR(255),
    fuel_type VARCHAR(255),
    make VARCHAR(255),
    model VARCHAR(255),
    plate_number VARCHAR(255),
    vin VARCHAR(255) NOT NULL,
    year INTEGER NOT NULL,
    person_id BIGINT,
    vehicle_id BIGINT,
    CONSTRAINT UK_vehicles_vin UNIQUE (vin),
    CONSTRAINT FK_vehicles_person FOREIGN KEY (person_id) REFERENCES persons(id),
    CONSTRAINT FK_vehicles_vehicle_type FOREIGN KEY (vehicle_id) REFERENCES vehicle_type(id)
);

-- ----------------------------
-- Table structure for vehicle_registrations
-- ----------------------------
CREATE TABLE IF NOT EXISTS vehicle_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expiry_date DATE,
    issue_date DATE,
    registration_number VARCHAR(255) NOT NULL,
    vehicle_id BIGINT,
    CONSTRAINT UK_vehicle_registrations_registration_number UNIQUE (registration_number),
    CONSTRAINT UK_vehicle_registrations_vehicle_id UNIQUE (vehicle_id),
    CONSTRAINT FK_vehicle_registrations_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
);
